# Generated by Django 3.1.4 on 2020-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('company_position', models.CharField(max_length=100)),
                ('appointment_time', models.CharField(max_length=100)),
                ('additional_question', models.CharField(max_length=100)),
            ],
        ),
    ]
